### ISSUE TITLE
Singletons

### ISSUE THREAD

**Issue by hiqsol** [yiisoft/di#22]
Does this implementation support singletons declarations? (Like yii2 di)

**Comment by samdark** [comment]
It supports singletons only.

**Comment by SilverFire** [comment]
I've never noticed this before. I don't think it's corrent

**Comment by samdark** [comment]
Why?

**Comment by SilverFire** [comment]
Because

**Comment by SilverFire** [comment]
:) Will explain a bit later

**Comment by SilverFire** [comment]
The main goal of container is to provide object built by the defined rules. When we talk about the DIC as a Service Locator, then it makes sense to have only singletons, because services must be stateless. However, there are also stateful classes, that cannot be reused and therefore created instances should not be saved.

A good comparison will be two classes from Yii: Connection (DB) and a Widget. While the first one should always act as a singleton, the second one depends. Here are two widgets:

```php
class LatestPostsWidget
{
    public function __construct(PostFormatter $postFormatter, Cache $cache)
    {
        // assign
    }
    
    public function render()
    {
        // find posts, render, cache
    }
}
```

```php
class UserTopPosts
{
    public function (User $user, PostFormatter $postFormatter, Cache $cache)
    {
        // assign
    }
    
    public function run()
    {
        // get posts of $this->user, format, cache
    }
}
```

It makes perfect sense to store object the first widget class, but it's absolutely useless for the second one.

Partially I do agree, that the second case can be redone with a factory of widgets, but I think there is a lot of existing code that will be broken when every object registered in DI will become a singleton

**Comment by samdark** [comment]
The issue with using container as a factory is that you need to pass parameters for objects created. Means that you'll have to access container methods directly. Thus, you'll explicitly reference container making your classes dependent on it.

**Comment by SilverFire** [comment]
Truth.

**Comment by SamMousa** [comment]
@samdark I disagree with your reasoning.
Yes the DI container should never be referenced directly, but making the assumption that all services are stateless is too strict.

If anything in the dependency graph of an object created by the DI container contains any configuration is it reasonable to assume that all those configuration settings cannot be changed?
For example the database component has a `charset` property, a `username` property and so on...
If I am passed an instance via DI, I have a pretty good idea of how to change it, since it implements some interface.
However using that interface to change the object would result in any code after to get injected with my altered version; which seems very intuitive.

If things created by the DI container have no state, then in my opinion that is a reason NOT to make them singletons, they have no state anyway.
The reason to create a singleton is if they actually DO have state and I want to reuse it (consider things like the PDO connection to the database).

**Comment by hiqsol** [comment]
@SamMousa I didn't get your idea. Can you please explain a bit more what's the problem.
You are talking about state but singletons are not about state.
In this context "singletons" means only that container creates object once and always returns same objects with every `$container->get()`.

**Comment by samdark** [comment]
It is perfectly fine for it to be mutable. For example, it could hold DB connection instance. Of course, there are bad cases to count against.

**Comment by SamMousa** [comment]
But why make singletons by default?

**Comment by samdark** [comment]
Because intended usage of DI container is to hold/inject services. Using it as a factory isn't its primary use case. See PSR meta document about it.

**Comment by SamMousa** [comment]
I read the documents; but there's also still ongoing discussion about the upside and downside of requiring singletons. The PSR11 spec is not strict about it and uses also mentions that users must not depend on getting the same value for every call even though implementations should do this.

This is basically the same discussion:
https://github.com/container-interop/container-interop/issues/69
