### ISSUE TITLE
Refactor configuration array

### ISSUE THREAD

**Issue by hiqsol** [yiisoft/di#67]
At the moment we have configuration array like this:

```php
    $config = [
        '__class' => MyClass::class,
        '__construct()' => [
            'param1' => 'value1',
            'param2' => 'value2',
        ],
        'prop' => 'value',
        'aMethod()' => ['arg1', 'arg2'],
    ];
```

We could redo it this way:

```php
    $config = [
        '__class' => MyClass::class,
        'param1' => 'value1',
        'param2' => 'value2',
        '__configure' => [
            'prop' => 'value',
            'aMethod()' => ['arg1', 'arg2'],
        ],
    ];
```

The convention will be throw away all items starting with '__' and use everything else as constructor params (to allow adding other special configuration options later).

This way is more convenient for classes with normal constructors which is what we aim to.
I have actually working big application switched to Yii 3 and in practice, there are more constructor parameters then properties configuration.

**Comment by FabrizioCaldarelli** [comment]
Why do you need to create '__configure' key? What is it for?

**Comment by hiqsol** [comment]
'__configure' is for additional initialization after construction.
E.g. setting props which are not available as constructor arguments. And calling methods.
It is convenient for classes having many optional properties which you don't put into the constructor.

**Comment by FabrizioCaldarelli** [comment]
Could not put additional initialization after construction in "init()" method?

So it would be usable also from standard constructor.

I don't find the need to setting '__configure', instead a common init() method.

**Comment by samdark** [comment]
In your example constructor parameters are named. In fact, they are not. How would it actually look like?

**Comment by hiqsol** [comment]
As it is done currently: apply array_values before using it. Given keys are not used.

**Comment by FabrizioCaldarelli** [comment]
If we had for each class last object defined as array ($config),
we could know that it is DI to do the call, checking the presence of __class
key inside $config array

```
<?php 
class BaseObject
{
    function __construct($config = [])
    {
        \yii\di\AbstractContainer::configure($this, $config);
    }
}

class MyClass
{
    private $importantField;

    function __construct(string $myImportantField, ...., $config = [])
    {
        if(isset($config['__class']) == false)
        {
            $this->importantField = $myImportantField
            parent::__construct($config);
        }
        else
        {
            // It is called by DI
        }
    }

    function init() 
    {
        // here some other initializations
    }
}
```

So I can create object with

```
$myObject = new MyClass('this is important value');
```

Instead, from configuration array point of view: 

```
$config = [
    '__class' => MyClass::class,
    'importantField' => 'content of important field'
]
```

DI should do these steps:

1) Create the object, $myClass = new ReflectionClass("MyClass");
2) Call $myObject = $myClass->newInstance($config);
3) \yii\di\AbstractContainer::configure($myObject, $config);
4) Previous call will check if the object is instance of MyClass

**Comment by SamMousa** [comment]
Both are the same to me just small syntactic difference

**Comment by FabrizioCaldarelli** [comment]
I've updated the source, using `newInstanceWithoutConstructor`, so we are not forced to have a variable parameters constructor.

**Comment by FabrizioCaldarelli** [comment]
> Both are the same to me just small syntactic difference

I think that for developer this is simpler, because syntax is equal to Yii2.

**Comment by SamMousa** [comment]
Yeah just saying I don't have an opinion, count my vote as blank

**Comment by samdark** [comment]
As @hiqsol pointed out, properties will be used less and less as we'll move towards constructor and setters. That is true. But while the proposal syntax is a bit shorter, I think it is more complicated.

Let's look at original:

```php
  $config = [
        '__class' => MyClass::class,
        '__construct()' => [
            'param1' => 'value1',
            'param2' => 'value2',
        ],
        'prop' => 'value',
        'aMethod()' => ['arg1', 'arg2'],
    ];
```

Here we have three types of items and they're all flat:

1. Class name.
2. Properties.
3. Method calls. One of the methods is `__construct()` and it's intuitively understandable.

New syntax:

```php
    $config = [
        '__class' => MyClass::class,
        'param1' => 'value1',
        'param2' => 'value2',
        '__configure' => [
            'prop' => 'value',
            'aMethod()' => ['arg1', 'arg2'],
        ],
    ];
```

Here we have:

1. Class name.
2. Constructor parameters that you should know about and may confuse with properties.
3. Special `__configure` element inside of which there are special meanings.
4. Property values that work within `__configure` only.
5. Method calls that work within `__configure` only.

So overall, I am for keeping longer syntax with less rules and exceptions.

**Comment by FabrizioCaldarelli** [comment]
Are you sure that we need __configure key? 

In my example, I have shown that it is not useful

**Comment by samdark** [comment]
@FabrizioCaldarelli would you please post a full example for the same object configuration as in the 1st @hiqsol post?

**Comment by hiqsol** [comment]
Also we could implement detection of constructor params with reflection so configuration could be:

```php
  $config = [
        '__class' => MyClass::class,
        'param1' => 'value1',
        'param2' => 'value2',
        'prop1' => 'value1',
        'prop2' => 'value2',
        'aMethod()' => ['arg1', 'arg2'],
    ];
```

(though not the way @FabrizioCaldarelli  says, it will require more difficult implementation)

Actually, I like this configuration :) 
I know it's problems also. But I think usability is important.

**Comment by samdark** [comment]
@hiqsol this way you won't be able to tell what is what. Would be confusing.

**Comment by hiqsol** [comment]
Is that so much important?
As a class user I just want to set object props.

On the other hand it allows to refactor class (redo property to constructor param or vice versa) without changing config.

**Comment by FabrizioCaldarelli** [comment]
> @FabrizioCaldarelli would you please post a full example for the same object configuration as in the 1st @hiqsol post?

Sure

```php
<?php 
class BaseObject
{
    function __construct($config = [])
    {
        // AbstractContainer will check if object is instance of Initiable.
        // If so, it will call init() method
        \yii\di\AbstractContainer::configure($this, $config);
    }

}

class MyClass extends BaseObject
{
    private $param1;
    private $param2;

    function __construct($param1, $param2)
    {
        $this->param1 = $param1;
        $this->param2 = $param2;
        parent::__construct();
    }
}
```

Using standard constructor way

`
$myObject = new MyClass('this is param1', 'this is param2');
`

Using DI

```php
$config = [
    '__class' => MyClass::class,
    'param1' => 'this is param1',
    'param2' => 'this is param2'
]
```

$myClass = new ReflectionClass("MyClass");
$myObject = $myClass->newInstanceWithoutConstructor();
\yii\di\AbstractContainer::configure($myObject, $config);

**Comment by FabrizioCaldarelli** [comment]
@samdark I don't know what is the purpose and job of `prop` and `aMethod()`.

What are they for?

**Comment by samdark** [comment]
`prop` is for setting a public property directly. `aMethod()` is for calling a class method right after its creation.

**Comment by FabrizioCaldarelli** [comment]
1) prop : I've not tryed, but using AbstractContainer::configure will not set all properties, including those public?

2) `aMethod`. I don't understand because I'd call a method from a static configuration array, but I think that this job should be managed by AbstractContainer::configure, that should check if $config key is a function and in that case call it passing parameters. Generic class should not handle dynamic function invocation.

**Comment by samdark** [comment]
I have no doubt that it would technically work. I'm worried about such syntax clarity.

**Comment by samdark** [comment]
> I'm curios: what are cases in which I needed to call method from static configuration array, after object creation?

For example, a component with optional logging:

```php
class TwitterPoster
{
    private $logger;
    private $twitterApi;

    public function __construct(TwitterApi $twitterApi)
    {
        $this->twitterApi = $twitterApi;
    }

    public function setLogger(Logger $logger)
    {
        $this->logger = $logger;
    }

    public function post($text)
    {
        $this->twitterApi->post($text);
        if ($this->logger !== null) {
            $this->logger->log($text . ' post to twitter');
        }
    }
}
```

config:

```php
   $config = [
        '__class' => TwitterPoster::class,
        '__construct()' => [
            'twitterApi' => ...,
        ],
        'setLogger()' => [...],
    ];
```

**Comment by FabrizioCaldarelli** [comment]
What about this:

config:

```php
   $config = [
        '__class' => TwitterPoster::class,
        'twitterApi' => [
            '__class' => TwitterApi::class,
            'accessToken' => 'myAccessToken'
        ],
        'logger' => [
            '__class' => Logger::class
            'target' => 'file'
        ]
    ];
```

class:

```php
class TwitterPoster extends BaseObject
{
    private $logger;
    private $twitterApi;

    public function __construct(TwitterApi $twitterApi)
    {
        $this->twitterApi = $twitterApi;
        parent::__construct();
    }

    public function post($text)
    {
        $this->twitterApi->post($text);
        if ($this->logger !== null) {
            $this->logger->log($text . ' post to twitter');
        }
    }
}
```

Using DI:

```php
$myClass = new ReflectionClass("TwitterPoster");
$myObject = $myClass->newInstanceWithoutConstructor();
\yii\di\AbstractContainer::configure($myObject, $config);
```

Obviously is the job of AbstractContainer::configure to create inner object and fill properties.

**Comment by samdark** [comment]
I don't like class design where it isn't able to work without a specific feature of DI container implementation (if there's no mistake and logger is private intentionally).

**Comment by FabrizioCaldarelli** [comment]
Mmmm ... I didn't get your answer.

**Comment by rob006** [comment]
>  As a class user I just want to set object props.

As a developer you want a clear and readable configuration, it is much harder to understand what is happening when you mix properties and constructor arguments in single array.

**Comment by samdark** [comment]
OK.

1. What do you think about [naming clash I've mentioned](https://github.com/yiisoft/di/issues/67#issuecomment-451297704)?
2. Also there is a slight difference between properties and constructor arguments. Properties are named. Constructor arguments are positional. Can you tell what's wrong in the following case?

```php
   $config = [
        '__class' => TwitterPoster::class,
       'logger' => [...],
       'twitterApi' => [...],
    ];

class TwitterPoster
{
    public __construct($twitterApi, $logger)  { ... }
}
```

**Comment by rob006** [comment]
> Situation with property vs constructor param is similar

For me it is completely different. Virtual properties works only because they're acting like properties, there is no additional magic here. Treating constructor arguments as properties is definitely different thing - it requires too much assumptions and magic to make it work.

**Comment by machour** [comment]
A few thoughts:

* Since we're trying to encourage constructors instead of properties, I like the initial proposal in this issue (with the `__configure` key). My "main" array entries are for the constructor, it's clear. 

* The [mixed constructor/properties](https://github.com/yiisoft/di/issues/67#issuecomment-451259847) proposal, while having an interesting syntax, would be really confusing. I'd like to see a clear distinction in my array, and not having to mentally remember what was supposed to go where, who's a constructor param and who's a property.

* The fact that we're discarding constructors params names using `array_values()` looks problematic to me. When I use a key based array, I expect the order of my items to have no impact. (some people event sort them alphabetically)

Using the provided keys to lookup the variable name in the constructor call and pass it in the accurate position would be better:

- No risks of positioning errors
- If the parameter name doesn't exist: throw an exception
- If later you decide to switch arguments positions in your `__constructor` signature, your code base won't be affected. (with array_values, I'll have to scan all initializations in my code, even for subclasses, and change ALL occurrences hoping I didn't forget a single one.

**Comment by samdark** [comment]
Another thing about virtual properties is the fact that they are supported only if you inherit from `BaseObject`. DI is able to configure any objects regardless if they are Yii-specific or not and it should stay like that.

**Comment by rob006** [comment]
> I was talking about my own application code, not Yii's.

Why do you want to do something like this for your own code? Such tricks are mostly useful for 3rd-party libraries, and they will follow PHP BC rules, where changing parameter name is not BC breaking change. Universal DI library should not create excessive rules and assumptions, because there will always be libraries not aware of these rules. DI library should adapt to the PHP ecosystem, not vice versa.

**Comment by samdark** [comment]
Discussed once again with @hiqsol and decided not to touch current syntax. Too many drawbacks.

**Comment by SamMousa** [comment]
I love the discussion guys! 
What are the specific goals we're trying to reach? I'm not a fan of the whole array configuration thing in general. I've heard one of the arguments is that it's easily to merge configuration when using arrays.

In my opinion this is not really the case without some strong assumptions (like that the alternative class also supports the same configuration settings).

From a more pure perspective it could be argued that parameters should be applied using something that looks similar to partial function application.

(FYI this is already supported since we support closures)
```php
[
    'someService' => function(DepA $a, DepB $b) {
        return new Service($a, $b, 145, "String param");
    }
]
```
Mainly the goal of DI is to inject dependencies, it does not mean that it must or even should do all configuration.
One advantage of this approach is that it also prevents accidental dumping of configuration (since Closures are hard to serialize or dump).

But this approach also has (properties that could be considered to be) drawbacks:

- Configuration should not be code?
- Harder to read if not used to it
- No config inheritance

What I like most about this approach is that it is native PHP and guarantees proper initialization or hard crashes. This is not the case if you use setter injection.
The explicitness of this would even allow automated checks like _can we initialize all dependencies?_.

Note that when it comes to configuration there is no real abstraction possible since I must now about the concrete class if I'm to configure it. Alternatively I could configure it by calling functions defined in its interface; for which case a closure still works:

```php
[
    'someService' => function(ServiceInterface $service) {
        $service->setSomething('abc');
        return $service;
    }
]
```

Just my 2 cents; I don't think we should drop support for array configuration, but personally I prefer to use it only in the simplest of cases.
